### PR TITLE
Allow to optionally show "Total" in most dashboard entry types

### PR DESCRIPTION
**Pull request by hulmgulm**
This is my first attempt to implement https://github.com/traggo/server/issues/88

The Dashboard Entry Editor allows to choose Total Hidden/Visible for all table types:
image
image

Sample dashboard:
image

### CODE REVIEW

**Comment by hulmgulm** [comment]
Small UI change. This looks better:
image

**Comment by hulmgulm** [comment]
Added total to line and bar chart tool tips:
image

Different label for switch depending on entry type:
image
image
image

**Comment by iuslkae** [comment]
Please review this @jmattheis @simhnna 
;')

**Review by iuslkae — COMMENTED** [review]
looks fine

**Review by iuslkae — APPROVED** [review]
🤏😏

**Comment by ericu109** [comment]
Having this as an option would be great for my use case, as I'm currently using Traggo to track billable hours on consulting projects.  I often wonder the total time logged for the day against different projects, and I pretty much never have more than one entry going at the same time.

**Comment by eitch** [comment]
Hi guys, what is the status of this PR? I would like this feature too

**Comment by jmattheis** [comment]
@eitch see #88

**Comment by maximecurioni** [comment]
+1

I look at my traggo dashboard 10x a day with daily, weekly and monthly hours broken down by client, and I'd love to have the total automatically computed for me, rather than doing it in my head 😄

**Comment by Minnowo** [comment]
Is this waiting on anything? I pulled the code and everything looks good.

**Comment by eitch** [comment]
@hulmgulm Do you perhaps push this to a docker registry for use?

**Comment by hulmgulm** [comment]
This feature is ready to be merged for a long time now and many people are asking for it. I don't want to create a fork of Traggo. @jmattheis @simhnna, what do I need to do get this PR merged?

**Comment by jmattheis** [comment]
@hulmgulm Yeah, you're right. I'll try to review the PR this week and then create a release for it.

**Review by jmattheis — APPROVED** [review]
Thanks for the contribution! I've made some small changes (see fixups)
* add default:false for total sql field
* refactor the summing of the time spans to use reduce
* move the getTotalTitle method

**Comment by hulmgulm** [comment]
Vielen Dank Jannis!

**Comment by sdykae** [comment]
@jmattheis congrats, took years but finally 👏

**Pull request merged**
